# 项目相关配置
geekplus:
  param:
    expireTime: 3600
    name: geekplusxyz
  # 名称
  name: GeekPlusXYZ
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2023
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/maike/uploadPath，Linux配置 /home/maike/uploadPath）
  filePath: /home/geekplus/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

server:
  port: 8090
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: GeekPlusXYZ
  mail:
    username: geekplus@hotmail.com
    password: 135790cpp@XT
    host: smtp.office365.com
    port: 587
    protocol: smtp
    default-encoding: UTF-8
  web:
    resources:
      static-locations: classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      username: root
      password: 123456cpp
      #url: jdbc:mysql://localhost:3306/geekplusadmin?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
      url: jdbc:mysql://43.133.254.75:3306/geekplusxyz?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: on
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: on
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,slf4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      useGlobalDataSourceStat: on
      defaultAutoCommit: on # 事物自动提交
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username:
        login-password:
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      ###解决项目自动重新编译后接口报404的问题
      poll-interval: 3000
      quiet-period: 1000
  freemarker:
    cache: false
    check-template-location: false
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/template/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html; charset=utf-8
    mode: LEGACYHTML5
  #redis配置
  redis:
    #redis服务地址 端口 密码
    host: 43.133.254.75
    #host: 127.0.0.1
    port: 6379
    password: 123456cpp
    #Redis数据库索引（默认为0）
    #database: 0
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 80
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        #连接池中的最大空闲连接
        max-idle: 30
        #连接池中的最小空闲连接
        min-idle: 5
    #连接超时时间（毫秒）
    timeout: 9000
mybatis:
  #config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.maike.webapp.function.domain
  configuration:
    cache-enabled: on
    use-generated-keys: on
    default-executor-type: reuse
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #security:
  #  basic:
  #    enable: false
  #    username: geekplus
  #    password: 123456cjj
  #pagehelper分页插件配置
  #pagehelper:
  #  helperDialect: mysql
  #  reasonable: true
  #  supportMethodsArguments: true
  #  params: count=countSql
openai:
  api:
    key: sk-erbfhjrbfhjebhjefbhfberhjbfheb
